# Command64 v1.0 by @tbm00
# https://github.com/tbm00/Command64/

# By default, everything is disabled.
# You should configure each module to your own liking.
# The predefined config is an example to give you and idea of what
# you can do when using this plugin with other plugins, like EssentialsX
# LuckPerms, PlayerParticles, SpecializedCrates, and MythicMobs.

# -------------------------------------------------------------------------------------- #
# joinCommandEntries get ran by the console when a player 
# (with the correct permission) connects to the server.
# ---------
# <player> == player who joined
# -------------------------------------------------------------------------------------- #
joinCommandEntries:
  enabled: false
  '1':
    enabled: false
    checkPerm: "group.particlebase"
    checkPermValue: false
    tickDelay: 10
    consoleCommands:
      - "pp reset <player>"
  '2':
    enabled: false
    checkPerm: "group.donor1"
    checkPermValue: true
    tickDelay: 10
    consoleCommands:
      - "say Welcome back to the server <player>!"
  '3':
    enabled: false
    checkPerm: "group.donor1"
    checkPermValue: false
    tickDelay: 10
    consoleCommands:
      - "say <player>, why haven't you donated?"
      - "say Gimme yo money!"
  # Add more entries as needed


# -------------------------------------------------------------------------------------- #
# customCommandEntries get ran by the console when the console, or
# a player (with the correct permission), uses the associated custom subcommand.
# ---------
# <sender> == player who used the command
# <argument> == string included as running command's argument
# ---------
# If wanted, you can add an inventory check to any custom command entry.
# If so, invCheck.checkOnPlayer should be "ARGUMENT" or "SENDER".
# ---------
# If wanted, you can add "-d <X>" when running any custom command to delay the console
# commands for X ticks.
# -------------------------------------------------------------------------------------- #
customCommandEntries:
  enabled: false
  '1': # Usage: "/cmd save"
    enabled: false
    usePerm: "command64.admin"
    usePermValue: true
    customCommand: "save"
    consoleCommands:
      - "say <sender> is saving the server!"
      - "save-all"
  '2': # Usage: "/cmd stop"
    enabled: false
    usePerm: "command64.admin"
    usePermValue: true
    customCommand: "stop"
    consoleCommands:
      - "say <sender> is stopping the server!"
      - "stop"
  '3': # Usage: "/cmd promotedonor <argument>" i.e. "/cmd promotedonor Notch"
    enabled: false
    usePerm: "command64.supermod"
    usePermValue: true
    customCommand: "promotedonor"
    consoleCommands:
      - "lp user <argument> promote donor"
      - "say <argument> donated to the server and was promoted by <sender>!"
  '4': # Usage "/cmd boss-fight-start"
    enabled: false
    usePerm: "command64.supermod"
    usePermValue: true
    customCommand: "boss-fight-start"
    consoleCommands:
      - "mm mobs spawn BossMinion -t world,-677,46,727"
      - "mm mobs spawn BossMinion -t world,-667,46,726"
      - "mm mobs spawn BossMinion -t world,-677,52,727"
      - "mm mobs spawn BossMinion -t world,-667,52,726"
      - "mm mobs spawn BossMinion -t world,-672,52,732"
      - "mm mobs spawn BossMinion -t Tadow,-673,52,722"
      - "mm mobs spawn BossMob -t world,-672,36,727"
      - "broadcast &bBoss fight started!"
      - "cmd -d 1200 boss-fight-round2" # 1 minute delay
  '5': # Intended Usage "/cmd -d <tickDelay> boss-fight-round2" i.e. "/cmd -d 1200 boss-fight-round2"
    enabled: false
    usePerm: "command64.supermod"
    usePermValue: true
    timerCommand: "boss-fight-round2"
    consoleCommands:
      - "mm mobs spawn BossMinion -t Tadow,-677,36,727"
      - "mm mobs spawn BossMinion -t Tadow,-667,36,726"
      - "mm mobs spawn BossMinion -t Tadow,-672,46,732"
      - "mm mobs spawn BossMinion -t Tadow,-673,46,722"
      - "mm mobs spawn BossMinion -t Tadow,-677,52,727"
      - "mm mobs spawn BossMinion -t Tadow,-667,52,726"
  '6': # Usage: "/cmd givekey <argument>" i.e. "/cmd givekey Notch"
    enabled: false
    usePerm: "command64.supermod"
    usePermValue: true
    customCommand: "givekey"
    consoleCommands:
      - "crates forceopen Crate32 <argument>"
    invCheck:
      checkIfSpaceBeforeRun: true
      checkPlayer: "ARGUMENT"
      ifNoSpaceConsoleCommands:
        - "msg <argument> &4You do not have enough space in your inventory... &cYou have two minutes to make room for your reward!"
        - "cmd -d 2400 givekey-try2 <argument>" # 2 minute delay
  '7': # Intended Usage: "/cmd -d <tickDelay> givekey-try2 <argument>" i.e. "/cmd -d 2400 givekey-try2 Notch"
    enabled: false
    usePerm: "command64.admin"
    usePermValue: true
    customCommand: "givekey-try2"
    consoleCommands:
      - "crates forceopen Crate32 <argument>"
      - "msg <argument> &2Force opening Crate32..! &eHope you have space :)"
  # Add more entries as needed


# -------------------------------------------------------------------------------------- #
# itemCommandEntries get ran by the console when a player
# (with the correct permission) uses a custom item.
# ---------
# <player> == player who used the item
# <argument> == string included as running command's argument
# -------------------------------------------------------------------------------------- #
itemCommandEntries:
  enabled: false
  '1':
    enabled: false
    givePerm: "command64.give.spawncompass"
    givePermValue: true
    usePerm: "essentials.spawn"
    usePermValue: true
    consoleCommands:
      - "sudo <sender> spawn"
    key: "SPAWNCOMPASS"
    name: "&dSpawn Teleporter"
    item: "COMPASS"
    glowing: true
    lore:
      - "&5Teleports you to spawn"
  '2':
    enabled: false
    givePerm: "command64.give.staffpick"
    givePermValue: true
    usePerm: "essentials.break"
    usePermValue: true
    consoleCommands:
      - "sudo <sender> break"
    key: "STAFFPICK"
    name: "&0Staff Pickaxe"
    item: "GOLDEN_PICKAXE"
    glowing: true
    lore:
      - "&4Be careful!"
  # Add more entries as needed