name: Command64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.command64.Command64
api-version: 1.17
commands:
  cmd:
    description: Base command for Command64
permissions:
  command64.help:
    description: Ability to display the command list
    default: op